# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

env:
  global:
  - PROTOBUF_VERSION=3.6.1
  - PATH="$HOME/protoc/bin:$PATH"

install:
- curl -Lo protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
- unzip -d "$HOME/protoc" protoc.zip

script:
- protoc --js_out=/tmp embedded_sass.proto
