name: CI

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  protoc:
    name: "Validate proto"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "3.x", repo-token: "${{ github.token }}" }
      - name: Generate protobuf code
        run: protoc --js_out=/tmp embedded_sass.proto

  versions:
    name: "Validate versions"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Check versions match
        run: |
          if ! (grep -q '\-dev$' VERSION ||
              [[ "$(head -n 1 CHANGELOG.md)" == "## $(cat VERSION)" ]]); then
            echo "VERSION file doesn't match CHANGELOG version."
          fi

  tag:
    name: "Tag release"
    runs-on: "ubuntu-latest"
    if: |
      github.event_name == 'push' &&
          github.repository == 'sass/embedded-protocol' &&
          github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get version information
        id: version-info
        run: |
          echo "::set-output name=VERSION::$(cat VERSION)"
          echo "::set-output name=VERSION_MODIFIED::$(
            git diff --quiet HEAD^ VERSION && echo true || echo false
          )"
      - name: Create release
        if: |
          steps.version-info.outputs.VERSION_MODIFIED == 'true' &&
            !endsWith(steps.version-info.outputs.VERSION, '-dev')
        run: |
          git config --global user.name 'SassBot'
          git config --global user.email 'sass.bot.beep.boop@gmail.com'
          git tag "${{ steps.version-info.VERSION }}"
          git push --tags
