name: CI

on:
  push:
    branches: [main, feature.*]
    tags: ['**']
  pull_request:

jobs:
  dart_tests:
    name: "Validate proto"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "3.x", repo-token: "${{ github.token }}" }
      - name: Generate protobuf code
        run: protoc --js_out=/tmp embedded_sass.proto

  tag:
    name: "Tag release"
    runs-on: "ubuntu-latest"
    if: "github.event_name == 'push' && github.repository == 'sass/embedded-protocol'"

    steps:
      - uses: actions/checkout@v2
      - name: Get version information
        id: version-info
        run: |
          echo "::set-output name=VERSION::$(cat VERSION)"
          echo "::set-output name=VERSION_MODIFIED::$(
            git diff --quiet HEAD^ VERSION && echo true || echo false
          )"
      - name: Create release
        if: |
          steps.version-info.VERSION_MODIFIED == 'true' &&
            !endsWith(steps.version-info.VERSION, '-dev')
        run: |
          git config --global user.name 'SassBot'
          git config --global user.email 'sass.bot.beep.boop@gmail.com'
          git tag "${{ steps.version-info.VERSION }}"
          git push --tag
