name: CI

on:
  push:
    branches: [master, feature.*]
    tags: ['**']
  pull_request:

jobs:
  dart_tests:
    name: "Validate proto"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with: { version: "3.x", repo-token: "${{ github.token }}" }
      - name: Generate protobuf code
        run: protoc --js_out=/tmp embedded_sass.proto

